// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwsorrjpsynogldgxgme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3c29ycmpwc3lub2dsZGd4Z21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjUxODcsImV4cCI6MjA1ODU0MTE4N30.p_0a1TedTXee-7a6ZxlR8lUnZmA4C-P-ljTgM4KH06k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);